INSERT INTO "element" VALUES(1,null,'point');
INSERT INTO "element" VALUES(2,null,'line');
INSERT INTO "element" VALUES(3,null,'plane');
INSERT INTO "element" VALUES(4,null,'sphere');
INSERT INTO "element" VALUES(5,null,'pointcloud');
INSERT INTO "element" VALUES(6,null,'cone');
INSERT INTO "element" VALUES(7,null,'circle');
INSERT INTO "element" VALUES(8,null,'cylinder');
INSERT INTO "element" VALUES(9,null,'ellipsoid');
INSERT INTO "element" VALUES(10,null,'hyperboloid');
INSERT INTO "element" VALUES(11,null,'nurbs');
INSERT INTO "element" VALUES(12,null,'paraboloid');
INSERT INTO "element" VALUES(13,null,'station');
INSERT INTO "element" VALUES(14,null,'readingPolar');
INSERT INTO "element" VALUES(15,null,'readingDistance');
INSERT INTO "element" VALUES(16,null,'readingDirection');
INSERT INTO "element" VALUES(17,null,'readingCartesian');
INSERT INTO "element" VALUES(18,null,'observation');
INSERT INTO "element" VALUES(19,null,'coordinatesystem');
INSERT INTO "element" VALUES(20,null,'sEntitiy angle');
INSERT INTO "element" VALUES(21,null,'sEntity distance');
INSERT INTO "element" VALUES(22,null,'sEntity temperature');
INSERT INTO "element" VALUES(23,null,'sEntity measurement series');
INSERT INTO "element" VALUES(24,null,'trafoParam');