INSERT INTO "element" VALUES(1,null,'circle');
INSERT INTO "element" VALUES(2,null,'cone');
INSERT INTO "element" VALUES(3,null,'cylinder');
INSERT INTO "element" VALUES(4,null,'ellipse');
INSERT INTO "element" VALUES(5,null,'ellipsoid');
INSERT INTO "element" VALUES(6,null,'hyperboloid');
INSERT INTO "element" VALUES(7,null,'line');
INSERT INTO "element" VALUES(8,null,'nurbs');
INSERT INTO "element" VALUES(9,null,'paraboloid');
INSERT INTO "element" VALUES(10,null,'plane');
INSERT INTO "element" VALUES(11,null,'point');
INSERT INTO "element" VALUES(12,null,'point cloud');
INSERT INTO "element" VALUES(13,null,'angle');
INSERT INTO "element" VALUES(14,null,'distance');
INSERT INTO "element" VALUES(15,null,'measurement series');
INSERT INTO "element" VALUES(16,null,'temperature');
INSERT INTO "element" VALUES(17,null,'slotted hole');
INSERT INTO "element" VALUES(18,null,'sphere');
INSERT INTO "element" VALUES(19,null,'torus');
INSERT INTO "element" VALUES(20,null,'direction');
INSERT INTO "element" VALUES(21,null,'position');
INSERT INTO "element" VALUES(22,null,'radius');
INSERT INTO "element" VALUES(23,null,'coordinate system');
INSERT INTO "element" VALUES(24,null,'station');
INSERT INTO "element" VALUES(25,null,'transformation parameters');
INSERT INTO "element" VALUES(26,null,'observation');
INSERT INTO "element" VALUES(27,null,'cartesian reading');
INSERT INTO "element" VALUES(28,null,'polar reading');
INSERT INTO "element" VALUES(29,null,'distance reading');
INSERT INTO "element" VALUES(30,null,'direction reading');
INSERT INTO "element" VALUES(31,null,'temperature reading');
INSERT INTO "element" VALUES(32,null,'level reading');